question_data = [
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Han Solo's co-pilot and best friend, Chewbacca, is an Ewok.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Leonardo DiCaprio won an Oscar for "
                 "Best Actor in 2004;The Aviator.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The film 2001: A Space Odyssey was released on December 31st, 2000.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of"
                 " the movies Interstellar and The Martian.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "The 2010 film &quot;The Social Network is a biographical drama film about MySpace "
                 "founder Tom Anderson.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The word Inception; came from the 2010 blockbuster hit Inception.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Shaquille O'Neal appeared in the 1997 film Space Jam&.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In Alfred Hitchcock's film Psycho it is said he used chocolate syrup to "
                 "simulate the blood in the famous shower scene from ",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Foodfight!; earned less than $80,000 at box office.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]}
]
